### ISSUE TITLE
show the pnpm, npm and yarn install commands for an icon set

### ISSUE THREAD

**Issue by KraXen72** [antfu-collective/icones#183]
### Clear and concise description of the problem

Currently, i have to hover/visit the npm site to get the install command (to use with unocss)

### Suggested solution

show the intallation command under/next to icon collection name, like this:
```
pnpm | yarn | npm
---
pnpm add @iconify-json/logos -D
```
![image](https://github.com/antfu/icones/assets/21956756/63b58cbd-f5ef-4279-9755-7acb43114511)

also, please include a copy command button for convenience. thanks.

### Alternative

show the id of the icon pack. user can type the rest of the command. Yes, the id is in url but it's ambiguous

### Additional context

developer experience

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sure, PR welcome
