### ISSUE TITLE
streamline:money-currency-bitcoin-circle-1-crypto-circle-payment-blockchain-finance-bitcoin-currency-money not working

### ISSUE THREAD

**Issue by IRediTOTO** [antfu-collective/icones#319]
### Describe the bug

This image url not working https://api.iconify.design/streamline:money-currency-bitcoin-circle-1-crypto-circle-payment-blockchain-finance-bitcoin-currency-money.svg?color=%23888888

### Reproduction

No need

### System Info

```Shell
No need
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by cyberalien** [comment]
It should be `https://api.iconify.design/streamline/money-currency-bitcoin-circle-1-crypto-circle-payment-blockchain-finance-bitcoin-currency-money.svg?color=%23888888`
