### ISSUE TITLE
Wrong license on CoreUI Free Icons?

### ISSUE THREAD

**Issue by benatkin** [antfu-collective/icones#323]
### Describe the bug

On here https://icones.js.org/collection/cil it says CC0 but if you look at the repo https://github.com/coreui/coreui-icons?tab=License-1-ov-file#readme that only applies to specific icons - brand and flag icons - while the ones I'm seeing in the icones page are the "free" ones

### Reproduction

Go to the two links above

### System Info

```Shell
Not applicable
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by cyberalien** [comment]
Quote from license file:

> Icons: CC BY 4.0 License (https://creativecommons.org/licenses/by/4.0/)
> In the CoreUI Icons Free download, the CC BY 4.0 license applies to all icons
> packaged as SVG and JS file types.

I don't see any issues

**Comment by benatkin** [comment]
> Quote from license file:
> 
> > Icons: CC BY 4.0 License (https://creativecommons.org/licenses/by/4.0/)
> > In the CoreUI Icons Free download, the CC BY 4.0 license applies to all icons
> > packaged as SVG and JS file types.
> 
> I don't see any issues

CC BY is a very different license from CC0.

<img width="570" alt="Screenshot 2024-07-17 at 10 37 21 PM" src="https://github.com/user-attachments/assets/ae6218a0-1bf7-4af1-b51d-1ba13c0e084d">

**Comment by cyberalien** [comment]
Oh right.

**Comment by cyberalien** [comment]
Fixed
