### ISSUE TITLE
Support icon search directly on the homepage?

### ISSUE THREAD

**Issue by wbxl2000** [antfu-collective/icones#325]
## Background

Sometimes I just want to search for an icon, rather than selecting a category first and then choosing an icon.

Now my backup plan is to select anyone category, then search for all icons through the 'All' tab.

<img width="666" alt="image" src="https://github.com/user-attachments/assets/a8d714be-fd59-4b3c-b4b7-bf7254bf4d38">

## Expect(Maybe)

<img width="666" alt="image" src="https://github.com/user-attachments/assets/c7f1699a-5232-42dc-a595-c9204a68b21c">

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
<img width="407" alt="Screenshot 2024-08-07 at 09 38 44" src="https://github.com/user-attachments/assets/ff9f4e1f-e6fb-4b2a-ac65-0c6085a38e0c">

Just press cmd and enter. It's already supported.
