### ISSUE TITLE
Add Azure icons

### ISSUE THREAD

**Issue by asdkant-bf** [antfu-collective/icones#334]
### Clear and concise description of the problem

I got here from the mermaidJS docs, specifically the Architecture Diagram type. The docs show an example using AWS icons from the "logos" collection, but I'm working with Azure and I can't find any azure icons.

### Suggested solution

include the icons from https://learn.microsoft.com/en-us/azure/architecture/icons/

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by cyberalien** [comment]
It is not open source.

Only open source icon sets are added.
