### ISSUE TITLE
Can't combine `outline` with `rounded`

### ISSUE THREAD

**Issue by mrleblanc101** [antfu-collective/icones#340]
### Clear and concise description of the problem

Not sure how this would affect other iconset, but Material Symbols has both `outline` (sharp) and `outline-rounded` variant.
Currently, it's impossible to combine both filters, which results in lots of duplicated icons when viewing:
![Screenshot 2024-12-16 at 3 51 15 PM](https://github.com/user-attachments/assets/9278ada8-bc58-4540-9ae6-bd780536ac9d)

### Suggested solution

Either we could allow to select both `outline` and `rounded`, or maybe we need to add combined options: `outline-sharp`, `outline-rounded`.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by mrleblanc101** [comment]
Google Fonts allows this by using a toggle to switch between `outlined` and `filled`.
![Screenshot 2024-12-16 at 4 05 10 PM](https://github.com/user-attachments/assets/4c6d2cce-aa77-49e3-bfeb-f81e57e2f61c)

**Comment by cyberalien** [comment]
Added. It will be included in Iconify icon sets data on next update run, so should be available on Icones after that.

**Comment by mrleblanc101** [comment]
@cyberalien Damn, that was quick 🙌

**Comment by mrleblanc101** [comment]
@cyberalien We should probably allow the same for Sharp variant ![image](https://github.com/user-attachments/assets/e125ac73-7f37-42ca-b0a1-ee6f9d8764de)

**Comment by cyberalien** [comment]
It is there: 6 suffixes for all variations.

<img width="1345" alt="Screenshot 2024-12-17 at 10 48 21" src="https://github.com/user-attachments/assets/a17c4603-a1e5-44cc-8f51-8c28f4331ca8" />

**Comment by mrleblanc101** [comment]
@cyberalien Oh, my bad. I see the new Outlin-rounded, but not Sharp-rounded. I'll wait a while for the next update ![image](https://github.com/user-attachments/assets/75e24579-5825-4513-91ce-585c8ecd6c0e)

**Comment by cyberalien** [comment]
Icones website is currently running previous version of icon sets data (Icones was updated about 2 hours ago, but icon sets package 1 hour ago), so it should be fixed on next dependencies update.

**Comment by mrleblanc101** [comment]
@cyberalien Yeah just curious since I expected both to be available at the same time since the changes are in the same commit 🤔
